### ISSUE TITLE
Broken due to capitalization of repo?

### ISSUE THREAD

**Issue by shogun168** [FunkeyFlo/ps5-mqtt#12]
### Description of the issue

Having an issue starting the addon and the same error appears when I try to uninstall so kind of stuck. It looks like because your repo isn't in lowercase, it gives me this error:

Failed to start add-on
Can't create container from addon_df2164f9_ps5_mqtt: 400 Client Error for http+docker://localhost/v1.41/containers/create?name=addon_df2164f9_ps5_mqtt: Bad Request ("invalid reference format: repository name must be lowercase")

And also means I can't remove the add-on either .. Any idea how to fix this?

### Addon version

0.6.2

### Platform

Supervisor 2022.07.0
Operating System 8.4
Frontend 20220707.1 - latest

**Comment by FunkeyFlo** [comment]
Hi, you are correct. I was working on adding an 'edge' version to the repo and accidently merged an incorrect file. I removed the image reference from the Stable version so it should be back to the way it was. Try running `check for updates` and installation should work afterwards.

**Comment by shogun168** [comment]
Ah I see .. hmmm, check for updates didn't work. It's not that I can't install, it's that I can't uninstall or start the addon. It's just stuck there.

**Comment by FunkeyFlo** [comment]
Have you tried performing a full restart of HA?

**Comment by shogun168** [comment]
Yep, tried that.

**Comment by FunkeyFlo** [comment]
Could you share the supervisor logs?

**Comment by shogun168** [comment]
Sure thing, attached full logs to post
[Full Logs Error.txt](https://github.com/FunkeyFlo/ps5-mqtt/files/9203011/Full.Logs.Error.txt)

**Comment by FunkeyFlo** [comment]
Just released version 0.6.3 which uses images instead of docker. Could you check whether updating works now. Otherwise I suggest joining the [discord](https://discord.gg/BnmvYHvz5N) for easier support. 😄

**Comment by shogun168** [comment]
That worked! Thanks for pushing that release out :)
