### ISSUE TITLE
PSN access error breaks flow

### ISSUE THREAD

**Issue by francois-pasquier** [FunkeyFlo/ps5-mqtt#121]
### Description of the issue

Would it be possible to make psn token errors non breaking for features like standby/sleep détection?

E.g: I don’t mind missing activity if my token is expired. I am really only using this for starting automations depending on the ps5 state.

The error is “There was a problem retrieving your PSN access code. Is your NPSSO code valid?”

### Addon version

Docker image 1.2.2

### Platform

N/A

**Comment by FunkeyFlo** [comment]
Agreed, NPSSO failure should not block other execution.

P.s.
_Please_ fill out the complete issue form. I don't have that much time ATM to work on this add-on and you'll help me save some time. 🙂

**Comment by francois-pasquier** [comment]
I didn’t fill the remaining entries as I am using it directly in docker 🙂

**Comment by FunkeyFlo** [comment]
Docker is still run on a specific architecture and can also output logs.

**Comment by FunkeyFlo** [comment]
@francois-pasquier `edge` version should fix this issue. Could you please confirm?
