### ISSUE TITLE
MQTT Documentation is easily confused with PS5 configuration.

### ISSUE THREAD

**Issue by Dracula2999** [FunkeyFlo/ps5-mqtt#14]
### Description of the issue

It's not clear that the port in the mqtt section does not refer to the PS5 but settings of the MQTT broker.

### Addon version

0.6.3

### Platform

Supervisor 2022.07.0

**Comment by FunkeyFlo** [comment]
Second time someone asked me this question so I guess it means the documentation isn't clear enough. Clicking on the link of [this part of the docs](https://github.com/FunkeyFlo/ps5-mqtt/blob/main/add-ons/ps5-mqtt/DOCS.md#mqtt) would tell you that the port that's being asked for is for the MQTT broker not the PS5.
