### ISSUE TITLE
PSN Login Not Working

### ISSUE THREAD

**Issue by danielsmith89** [FunkeyFlo/ps5-mqtt#141]
### Description of the issue

Hello,

I can get it working if I don’t set the PSN_ACCOUNTS value (albeit just power status), but as soon as I try and set this value to get the "playing" status working correctly, I'm getting this error in the logs:

```
022-12-01T21:48:01.730Z @ha:ps5:error FetchError: request to https://m.np.playstation.net/api/userProfile/v1/internal/users/XXXXXXXXXXXXX/basicPresences?type=primary failed, reason: getaddrinfo ENOTFOUND m.np.playstation.net
    at ClientRequest.<anonymous> (/app/node_modules/node-fetch/lib/index.js:1491:11)
    at ClientRequest.emit (node:events:527:28)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

### Addon version

1.3.0

### Platform

Core: core 2022.11.4
Running in Docker

**Comment by FunkeyFlo** [comment]
This issue was resolved >=1.2.2. are you 100% you're running the correct version?
Otherwise, please share your `docker-compose` confif.

**Comment by danielsmith89** [comment]
Thanks for the quick reply, turns out I wasn’t! The reason is I copied and pasted the docker-compose example from https://github.com/FunkeyFlo/ps5-mqtt/blob/main/docs/DOCKER.md and that has an old version coded into it. I’ve changed that to latest and it’s now working. Might be worth you updating that example docker-compose snippet :)

**Comment by FunkeyFlo** [comment]
That's also why the issue template prompts you to specify a version, hopefully reminding you to actually check before submitting.

Nonetheless I changed it to `latest` to keep this from happening again. 😘
