### ISSUE TITLE
[Feature request]: Add PS5 by passing the IP

### ISSUE THREAD

**Issue by klatka** [FunkeyFlo/ps5-mqtt#165]
### Is your feature request related to a problem? Please describe

My PS5 is not being discovered in my network setup (/23 network, no VLANs)

### Describe the solution you'd like

Additional field in configuration to set an IP address.
playactor should be used with this IP e.g. `playactor check --ip 192.168.1.30` 

### Describe alternatives you've considered

Any alternative to use my PS5 without being found by `playactor browse`

### Additional context

See https://github.com/FunkeyFlo/ps5-mqtt/issues/164

**Comment by ahmadnassri** [comment]
second this, I have multiple vlans, and assigning broadcast address is not helping (likely due to complex isolation rules in my network setup)

so would be much easier to just tell the plugin where the PS5 is by IP (since it's static) and avoid having to add firewall rules / broadcast address changes, etc ...

**Comment by klatka** [comment]
This is still needed

**Comment by SCCMOG** [comment]
+

**Comment by ahmadnassri** [comment]
still needed

**Comment by TMan1695** [comment]
Still needed

**Comment by RomaDomor** [comment]
Still needed

**Comment by KuChar91** [comment]
++

**Comment by VinceMasuka** [comment]
May we have this, please?

**Comment by DutchessNicole** [comment]
Also very much interested in being able to directly target a DDNS hostname or at least the IP. Browsing does not work across networks, and setting the broadcast address doesn't help if the HA host is not actually in the network we would like to scan.

**Comment by ZenoBell** [comment]
+1 for this please !
