### ISSUE TITLE
Fresh install, no configuration option 0.6.3

### ISSUE THREAD

**Issue by pvmil** [FunkeyFlo/ps5-mqtt#17]
### Description of the issue

After a fresh install (first install ever) the configuration tab of the plugin is empty. It only shows (my translation) "This add-on does not show configuration options to play with…"
Starting the add-on gives pop-up: "Missing required option 'host' in PS5 MQTT (df2164f9_ps5_mqtt)."

I checked for a configuration file in my configuration folder (as explained in the manual configuration) but it is not there.

### Addon version

0.6.3

### Platform

Home Assistant 2022.7.7
Supervisor 2022.07.0
Operating System 8.4

### Logs of the issue (if applicable)

No log, the plugin does not start

**Comment by FunkeyFlo** [comment]
If you could include the supervisor logs that would be great; you can find them under [System] > [Logs] > [Supervisor] (top right drop-down).

I've seen this behaviour before and flicking the start on boot or watchdogs switches a couple of times might resolve this. 

However, if you could include the supervisor logs that would be mighty fine! 😎
That way we can check whether it's an issue with the add-on or supervisor/HA.

**Comment by pvmil** [comment]
Hi Funkey (btw thanks for this plugin and your efforts),

My supervisor log:
`22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.check] Starting system checks with state CoreState.RUNNING
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_FAILED/ContextType.DNS_SERVER
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.DNS_SERVER_IPV6_ERROR/ContextType.DNS_SERVER
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.PWNED/ContextType.ADDON
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.TRUST/ContextType.SUPERVISOR
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.FREE_SPACE/ContextType.SYSTEM
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.checks.base] Run check for IssueType.SECURITY/ContextType.CORE
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.check] System checks complete
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.evaluate] Starting system evaluation with state CoreState.RUNNING
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.evaluate] System evaluation complete
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.fixup] Starting system autofix at state CoreState.RUNNING
22-07-29 22:57:43 INFO (MainThread) [supervisor.resolution.fixup] System autofix complete
22-07-29 23:00:18 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-07-29 23:00:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/snowzach/hassio-addons repository
22-07-29 23:00:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/FunkeyFlo/ps5-mqtt repository
22-07-29 23:00:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-07-29 23:00:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-07-29 23:00:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mKeRix/hassio-repo repository
22-07-29 23:00:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-07-29 23:00:21 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
22-07-29 23:00:24 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token
22-07-29 23:00:25 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:00:25 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:00:34 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/core_mosquitto
22-07-29 23:00:34 INFO (SyncWorker_3) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-addon-mosquitto with tag 6.1.2.
22-07-29 23:01:05 INFO (MainThread) [supervisor.addons] Add-on 'core_mosquitto' successfully installed
22-07-29 23:01:43 INFO (SyncWorker_2) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-mosquitto with version 6.1.2
22-07-29 23:01:46 INFO (MainThread) [supervisor.discovery] Sending discovery to Home Assistant mqtt from core_mosquitto
22-07-29 23:01:48 INFO (MainThread) [supervisor.services.modules.mqtt] Set core_mosquitto as service provider for mqtt
22-07-29 23:01:57 ERROR (MainThread) [supervisor.homeassistant.api] Error on call http://172.30.32.1:8123/api/hassio_push/discovery/06fc03d6bcc548ea9a56760558087d08: 
22-07-29 23:01:57 WARNING (MainThread) [supervisor.discovery] Discovery 06fc03d6bcc548ea9a56760558087d08 message fail
22-07-29 23:02:12 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-07-29 23:02:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/FunkeyFlo/ps5-mqtt repository
22-07-29 23:02:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-07-29 23:02:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-07-29 23:02:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
22-07-29 23:02:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mKeRix/hassio-repo repository
22-07-29 23:02:12 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-07-29 23:02:13 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/snowzach/hassio-addons repository
22-07-29 23:02:17 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:02:17 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:03:12 INFO (MainThread) [supervisor.backups.manager] Creating new partial backup with slug 049aa2b8
22-07-29 23:03:12 INFO (MainThread) [supervisor.backups.manager] Backing up 049aa2b8 store Add-ons
22-07-29 23:03:12 INFO (MainThread) [supervisor.addons.addon] Building backup for add-on core_zwave_js
22-07-29 23:03:18 INFO (MainThread) [supervisor.addons.addon] Finish backup for addon core_zwave_js
22-07-29 23:03:18 INFO (MainThread) [supervisor.backups.manager] Creating partial backup with slug 049aa2b8 completed
22-07-29 23:03:18 INFO (SyncWorker_5) [supervisor.docker.interface] Updating image homeassistant/amd64-addon-zwave_js:0.1.64 to homeassistant/amd64-addon-zwave_js:0.1.65
22-07-29 23:03:18 INFO (SyncWorker_5) [supervisor.docker.interface] Downloading docker image homeassistant/amd64-addon-zwave_js with tag 0.1.65.
22-07-29 23:03:49 INFO (SyncWorker_5) [supervisor.docker.interface] Stopping addon_core_zwave_js application
22-07-29 23:03:57 INFO (SyncWorker_5) [supervisor.docker.interface] Cleaning addon_core_zwave_js application
22-07-29 23:03:57 INFO (MainThread) [supervisor.addons] Add-on 'core_zwave_js' successfully updated
22-07-29 23:03:57 INFO (SyncWorker_1) [supervisor.docker.interface] Cleanup images: ['homeassistant/amd64-addon-zwave_js:0.1.64']
22-07-29 23:04:06 INFO (SyncWorker_0) [supervisor.docker.addon] Starting Docker add-on homeassistant/amd64-addon-zwave_js with version 0.1.65
22-07-29 23:04:06 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-07-29 23:04:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
22-07-29 23:04:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mKeRix/hassio-repo repository
22-07-29 23:04:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-07-29 23:04:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-07-29 23:04:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/snowzach/hassio-addons repository
22-07-29 23:04:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/FunkeyFlo/ps5-mqtt repository
22-07-29 23:04:06 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-07-29 23:04:11 INFO (MainThread) [supervisor.api.middleware.security] /host/info access from core_zwave_js
22-07-29 23:04:11 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:04:11 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:07:52 INFO (MainThread) [supervisor.auth] Auth request from 'core_mosquitto' for 'mqtt_user'
22-07-29 23:07:53 INFO (MainThread) [supervisor.auth] Successful login for 'mqtt_user'
22-07-29 23:08:35 WARNING (MainThread) [supervisor.addons.addon] core_mosquitto is already running!
22-07-29 23:09:33 INFO (MainThread) [supervisor.addons] Creating Home Assistant add-on data folder /data/addons/data/df2164f9_ps5_mqtt
22-07-29 23:09:33 INFO (SyncWorker_2) [supervisor.docker.interface] Downloading docker image ghcr.io/funkeyflo/ps5-mqtt/amd64 with tag 0.6.3.
22-07-29 23:11:10 INFO (MainThread) [supervisor.addons] Add-on 'df2164f9_ps5_mqtt' successfully installed
22-07-29 23:14:24 INFO (MainThread) [supervisor.updater] Fetching update data from https://version.home-assistant.io/stable.json
22-07-29 23:14:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/hassio-addons/repository repository
22-07-29 23:14:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/mKeRix/hassio-repo repository
22-07-29 23:14:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/thomasmauerer/hassio-addons repository
22-07-29 23:14:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/home-assistant/addons repository
22-07-29 23:14:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/FunkeyFlo/ps5-mqtt repository
22-07-29 23:14:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/esphome/home-assistant-addon repository
22-07-29 23:14:24 INFO (MainThread) [supervisor.store.git] Update add-on https://github.com/snowzach/hassio-addons repository
22-07-29 23:14:28 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:14:28 INFO (MainThread) [supervisor.store] Loading add-ons from store: 78 all - 0 new - 0 remove
22-07-29 23:20:22 INFO (MainThread) [supervisor.host.info] Updating local host information
22-07-29 23:20:24 INFO (MainThread) [supervisor.host.services] Updating service information
22-07-29 23:20:24 INFO (MainThread) [supervisor.host.network] Updating local network information
22-07-29 23:20:24 INFO (MainThread) [supervisor.host.sound] Updating PulseAudio information
22-07-29 23:20:24 INFO (MainThread) [supervisor.host.manager] Host information reload completed
22-07-29 23:30:24 INFO (MainThread) [supervisor.homeassistant.api] Updated Home Assistant API token`

**Comment by pvmil** [comment]
> If you could include the supervisor logs that would be great; you can find them under [System] > [Logs] > [Supervisor] (top right drop-down).
> 
> I've seen this behaviour before and flicking the `start on boot` or `watchdog` switches, in the add-on `info` tab, a couple of times might resolve this.
> 
> However, if you could include the supervisor logs that would be mighty fine! 😎 That way we can check whether it's an issue with the add-on or supervisor/HA.

Flicking the switches multiple times indeed solves the issue, configuration is available now. Thnx!
