### ISSUE TITLE
[Feature request]: Use refresh tokens rather than getting an access token every time the application starts

### ISSUE THREAD

**Issue by JeffersonBledsoe** [FunkeyFlo/ps5-mqtt#173]
### Is your feature request related to a problem? Please describe

The psn-api has support for using refresh tokens once an access token has expired. This means that the issue of NPSSO token's expiring won't be an issue, as the user doesn't need them after the initial authorization.

### Describe the solution you'd like

Everywhere an access token is fetched, check whether the access token has expired and if it has, use the refresh token to issue a new access token. See https://psn-api.achievements.app/authentication/using-your-refresh-token for an example of how this works

### Describe alternatives you've considered

.

### Additional context

.

**Comment by JeffersonBledsoe** [comment]
@FunkeyFlo I haven't been using PS5-mqtt long enough yet to hit the NPSSO limit. I assume it is still there as documented, but I didn't see a call to `exchangeRefreshTokenForAuthTokens` in the code so I assume this issue is relevant

**Comment by FunkeyFlo** [comment]
It is being used already: https://github.com/FunkeyFlo/ps5-mqtt/blob/main/ps5-mqtt/server/src/psn-account.ts#L156

The problem currently is rather that refresh tokens should be cached somewhere so the NPSSO doesn't need to be used when the app restarts.

**Comment by JeffersonBledsoe** [comment]
>It is being used already
I should have cloned the repo and looked instead of using the GitHub code search 🤦 

> The problem currently is rather that refresh tokens should be cached somewhere so the NPSSO doesn't need to be used when the app restarts.
I've not really dove much into the code, but is this a case of writing to disk on refresh token change? Considering there's no database, there's no use encrypting the token either right?

**Comment by FunkeyFlo** [comment]
Yes. And it also requires us to know which refresh token belongs to which account. Since multiple accounts can be used.

**Comment by rvanmaanen** [comment]
@FunkeyFlo: I came here looking to see if there was already someone who requested exactly this feature. In the latest reply you mentioned that you need to know which token belongs to which account. Can't we start off with a MVP version of this feature, only supporting this when a single account is used (which I assume is the majority of the cases). Or write the refresh token to disk and use the accountname as filename? I'm really no typescript hero, else I'd gladly make a PR :)
