### ISSUE TITLE
No Web UI

### ISSUE THREAD

**Issue by Hassefar** [FunkeyFlo/ps5-mqtt#18]
Hi

The web ui button is not available on my install. What I am missing here?
![image](https://user-images.githubusercontent.com/62770636/181861339-26f686dd-3924-46fe-ad90-2b5aaddb91ed.png)
![image](https://user-images.githubusercontent.com/62770636/181861372-ae21f62e-36a3-44ab-968f-577177075469.png)

**Comment by FunkeyFlo** [comment]
Because you need to start the add-on. It can't host a web application if it's not running..

Also, please do use the issue templates. 😬

**Comment by Hassefar** [comment]
Thank you very much. And sorry for not using the issues template - I am new to this.

Are there any documentation available for how to control the PS5 iteself? I.e. what topic and payload do I need to send?

**Comment by Hassefar** [comment]
It may  be that I have not been able to configure it correctly. Once i try to login to get the URL, after everything is done I get the message: 
![image](https://user-images.githubusercontent.com/62770636/181907741-7de687e2-ce4a-4f22-90a0-1aaa6302a6b9.png)

**Comment by FunkeyFlo** [comment]
Yes, there is documentation. It is actually even described in the pop up you get when connecting the PS5 as shown in the attached screenshot.

![Screenshot_20220730-131100](https://user-images.githubusercontent.com/4623715/181908448-712f8757-a916-4109-9a11-3e3f45d56bd5.png)

I am going to say this means the description in the web UI isn't clear enough and try to clear it up for the next release.

Also; questions like these are best posed in the discord. You'll probably get help a lot quicker and it enables us to reserve GitHub issues for:
- Bugs
- Feature Requests
- Documentation requests
- Improvements
- etc.

Cheers ❤️

**Comment by Hassefar** [comment]
sorry - the documentation is clear. My problem seems to be that the Sony Authentication is not currently working.
