### ISSUE TITLE
MQTT connection cannot be established (docker)

### ISSUE THREAD

**Issue by blysik** [FunkeyFlo/ps5-mqtt#195]
### Description of the issue

Hi!  I am using HA Core in docker, with mqtt in docker also.  I've setup ps5-mqtt in a container per your instructions, host networking, pointing to my valid broker. I've left user/password blank as my broker doesn't require them.

Unfortunately I'm seeing this error on startup:

```
Starting PS5-MQTT...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo ENOTFOUND null
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'null'
}
```

Broker is also running in a container with host networking, and I've tried referring to it with IP, as well as localhost, but with the same result.

Thanks!

### Addon version

1.3.1

### Platform

Not running in HAOS, but latest HA in docker.

### Logs of the issue (if applicable)

Starting PS5-MQTT...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^

Error: getaddrinfo ENOTFOUND null
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'null'
}

**Comment by FunkeyFlo** [comment]
- Are you able to connect to the broker using a different app/service, such as MQTT explorer?
- Please share your config
- Can connection be established if you *do* connect using a user and password?
- Please also share the *exact* HA version instead of "latest"

**Comment by blysik** [comment]
* Many of my other docker containers I run are using this same MQTT broker.  For example, HA itself, Frigate, etc..
* See the ENV variables I've set here:
  * <img width="1417" alt="Screenshot 2023-02-23 at 12 28 58 PM" src="https://user-images.githubusercontent.com/58610/221023439-551ffd04-1fa8-4a1e-9353-d125597f3ac4.png">
* I would have to enable auth on the broker, and everything else is not using auth, so I'd rather do that only as a last ditch effort.
* HA version is 2023.2.4, though it doesn't really matter since ps5-mqtt isn't able to start successfully yet.

Thanks for the quick response!

**Comment by FunkeyFlo** [comment]
Config seems to be fine, as far as I can tell.

> I would have to enable auth on the broker, and everything else is not using auth, so I'd rather do that only as a last ditch effort.

I understand it's inconvenient but if you could just try it for a moment, and if connection is succesful afterwards that would give me a sense of what might be going wrong. <3

**Comment by blysik** [comment]
Okay, so i followed the instructions on enabling auth, and a user/pass here: http://www.steves-internet-guide.com/mqtt-username-password-example/

then I set MQTT_USERNAME and MQTT_PASSWORD appropriately.  Still the same getaddrinto error.

Also note, that if I watch the mosquitto log, I do not see any connection attempt from ps5-mqtt.  It's not even getting to the auth part anyways, if that's the problem.

**Comment by blysik** [comment]
```hostname: 'null'``` is interesting.

```node:internal/process/promises:279
triggerUncaughtException(err, true /* fromPromise */);
^

Error: getaddrinfo ENOTFOUND null
at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
errno: -3008,
code: 'ENOTFOUND',
syscall: 'getaddrinfo',
hostname: 'null'
}````

What segment of code is this?  Is this an attempt to connect to the broker?

**Comment by blysik** [comment]
Looking for other examples of "Error: getaddrinfo ENOTFOUND null".

I found this: https://discuss.colyseus.io/topic/389/proxy-error-getaddrinfo-enotfound/4
```
Hello, each colyseus server will try to get it's ip address from process.env.SELF_HOSTNAME before falling back to internal-ip.

In some rare cases it appears internal-ip isn't working, so an easy fix is to set the SELF_HOSTNAME env variable for each server.
```

That's interesting.  It does feel like some sort of networking issue.

**Comment by FunkeyFlo** [comment]
Yeah, at first I thought it might not handle anonymous connections properly, but it seems it's just not able to find the broker host you're specifying. 
Are you 100% sure the IP you're specifying is correct? Otherwise maybe something's up with the network.

**Comment by blysik** [comment]
I've double checked the IP.  I've also tried with 'localhost', which is how HomeAssistant connects to the broker.  Same error.  I've even tried the IP, and bridge networking instead of host.  No luck there.  Something odd is going on with his container image.

**Comment by FunkeyFlo** [comment]
I don't know what to tell you, except that it is *incredibly* unlikely that it has to do with the container image. Since the release of this version (december 2022) there have not been *any* similar reports.

**Comment by blysik** [comment]
I hear you.  Would you be okay with leaving this open?  I'll continue to try and play with settings on my side, and update this issue with what I find.  At least it can help other people.  

Other data points:
 docker management is being handled by Portainer 1.24.0
ontop of a Centos 7.6.1810 system, 
docker-ce-20.10.6-3.el7.x86_64

**Comment by blysik** [comment]
Okay, so this was my fault.  I didn't fully read your instructions.  It all seemed pretty standard, so I skimmed.  But having to create my own run.sh, and modify the entrypoint is something pretty nonstandard. :)

Once I did that, I'm running fine.  Sorry for noise!

**Comment by blysik** [comment]
So a warning to all: completely read the instructions.
