### ISSUE TITLE
Failed to save config

### ISSUE THREAD

**Issue by taylordtriplett** [FunkeyFlo/ps5-mqtt#202]
### Description of the issue

I am getting the following error when attempting to save the PS5 MQTT Config(all person info replaced with stars).

Failed to save add-on configuration, Invalid list for option 'psn_accounts' in PS5 MQTT (df2164f9_ps5_mqtt). Got {'mqtt': {'host': '192.168.*.**', 'port': '****', 'user': 'MQTT User', 'pass': '********'}, 'logger': '@ha:ps5:*', 'device_check_interval': 5000, 'device_discovery_interval': 60000, 'account_check_interval': 5000, 'include_ps4_devices': False, 'psn_accounts': {}} 

This error occurs when I have the PSN_Accounts box filled in as well. Have tried both UI and Yaml edits with no success. 

### Addon version

1.3.1

### Platform

Home Assistant 2023.3.2
Supervisor 2023.03.1
Operating System 9.5
Frontend 20230306.0 - latest

**Comment by taylordtriplett** [comment]
Here you go! Sorry for the delay. 

mqtt: {}
logger: "@ha:ps5:*"
device_check_interval: 3000
device_discovery_interval: 60000
account_check_interval: 5000
include_ps4_devices: false
psn_accounts:
  - username: taylordtriplett
    npsso: "!secret a28**************************************sXxH"
    preferred_ps5: null

<img width="881" alt="Screenshot 2023-03-22 at 19 54 16" src="https://user-images.githubusercontent.com/74088797/227079019-0f1fda13-d820-46a5-9335-c8cd33e21432.png">

**Comment by FunkeyFlo** [comment]
Well the given error message tells you all you need to know: you're using `!secret` incorrectly.

(Recommended) Read the [HA Docs](https://www.home-assistant.io/docs/configuration/secrets/#using-secretsyaml) to learn how to use `!secret`. 

Or, use the npsso value withe the `!secret` prefix.

**Comment by NickVulkers** [comment]
For anyone running into this issue, the addon has to be restarted: https://community.home-assistant.io/t/how-to-use-secrets-yaml-in-addons/358504.
