### ISSUE TITLE
Issue with PS4 entity

### ISSUE THREAD

**Issue by bryeartem** [FunkeyFlo/ps5-mqtt#22]
### Description of the issue

I am not sure if you had the intention of supporting PS4s with this add-on, but when I setup the first version I already had the ps4 in my credentials.json I was using from a previous integration (PlayActor).  So my PS4 showed up and created an entity but it was unavailable.  I just ignored it assuming there was no support for the 4.  With your latest updates and the Web UI it appears to have the correct status for the PS4 and Standby/Awake States on the status page for each one but the entity remains unavailable.  I tried going through the Reauth steps on the 4 and everything appears to work correctly, and the WebUI still shows the 4 and the correct state, but the entity remains unavailable and I have this is my log: 
`2022-08-04T14:36:40.910Z @ha:ps5:error SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at /app/server/dist/redux/sagas/check-devices-state.js:65:38
    at step (/app/server/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/server/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)`

Should this be working for the PS4 or is there I way I can exclude it from discovery if not?  Your add-on seems to be very quick and reliable as far as the status of the PS5s so I was hoping to use that for the 4 instead of the official integration.  Thank you for your time.

### Addon version

0.7.0

### Platform

Core: 2022.8.0
Supervisor: 2022.07.0
OS: Debian 11

**Comment by FunkeyFlo** [comment]
Originally, I didn't intend for PS4's to be supported, as mentioned in the [FAQ](https://github.com/FunkeyFlo/ps5-mqtt#why-doesnt-this-add-on-support-playstation-4-devices). For reasons that I mentioned there.

I also took precautions to filter out PS4 devices by using filters in Playactor that apparently don't work. I can however add an additional filter that would be applied post Playactor discovery to still achieve this functionality.

However, I wasn't aware that my add-on delivers better performance than the PS4 integration that's currently available for HA.

So I'm now tempted to add a configuration option that allows you to filter out PS4 devices if you don't want this add-on picking them up. Meaning that you can opt-in for PS4 discovery with this add-on as well. That would however mean that, even though it's achievable for PS4's, PS4's would also only allow toggling Power state with this change.

Tell you what, I'll add the option mentioned above to the `edge` version and we'll see how it works.

**Comment by FunkeyFlo** [comment]
I've just updated the `edge` version of the add-on to include the change mentioned above. Would you mind trying it out to see if it behaves as expected? 😊 You might need to remove the previously discovered PS4 device in Home Assistant first. Also don't forget to disable the regular add-on before starting the edge version.

**Comment by bryeartem** [comment]
> However, I wasn't aware that my add-on delivers better performance than the PS4 integration that's currently available for HA.

Yes, my experience so far has been that PlayActor and the manually created switch entities don't reflect the state changes fast enough most of the time, and I have some automations that require the state to change for the Alexa response to be accurate.  So far it seems that your add-on is much more consistent in reflecting the state changes faster.  And that was part of the reason I was trying to get the PS4 to work through it, and the official PS4 integration seems to occasionally lose connection when we don't use it for awhile.
But thank you, I will try the edge version and see if it successfully filters out the PS4.  Thanks for your time, nice work with the Add-On.

**Comment by bryeartem** [comment]
Yes it appears to have ignored the PS4 after the initial discovery and no more errors in logs.  Thank you very much.
