### ISSUE TITLE
[Feature request]: Support for multiple users

### ISSUE THREAD

**Issue by wookash** [FunkeyFlo/ps5-mqtt#220]
### Is your feature request related to a problem? Please describe

I tried separating ‘PSN_ACCOUNTS’ environmental variable by comma, but it did not work, only one user is being recognised and successfully authenticated

```
[{"username": "username1", "npsso": "npsso1"}, {"username": "username2", "npsso": "npsso2"}]
```

### Describe the solution you'd like

I'd like to be able to track multiple users' activity

### Describe alternatives you've considered

tracking only 1 user

### Additional context

n/a

**Comment by FunkeyFlo** [comment]
This is a bug and not a feature request. Please fill out the appropriate issue template and resubmit your issue.
