### ISSUE TITLE
Multiple user accounts not working

### ISSUE THREAD

**Issue by wookash** [FunkeyFlo/ps5-mqtt#221]
### Description of the issue

I tried separating ‘PSN_ACCOUNTS’ environmental variable by comma, but it did not work, only one user is being recognised and successfully authenticated

```
[{"username": "username1", "npsso": "npsso1"}, {"username": "username2", "npsso": "npsso2"}]
```

### Addon version

ghcr.io/funkeyflo/ps5-mqtt/aarch64:latest

### Platform

Docker container, 2023.4.4

**Comment by FunkeyFlo** [comment]
- Could you share a more complete example of your config?
- Are the logs saying anything?
- Have you tried using the `.json` option for this specific setting?
