### ISSUE TITLE
Ports/networking for Docker installation

### ISSUE THREAD

**Issue by casabryant** [FunkeyFlo/ps5-mqtt#25]
### Description of the issue

The docker version works overall great, but it's unclear to me the networking requirements. I have it working by using host network mode as indicated in the documentation, as well as disabling UFW. I would like to be able to only open the firewall to the necessary ports, and potentially to avoid host network mode by exposing only the needed ports.

Is this possible? If so, which ports should I open? I have tried opening ports 8645, 997, and 9302, but that did not work for discovering my PS5.

### Addon version

ghcr.io/funkeyflo/ps5-mqtt/amd64:0.7.1

### Platform

Docker: amd64:0.7.1
Operating System: Ubuntu 22.04

**Comment by FunkeyFlo** [comment]
Unfortunately this seems to be a limitation of the [playactor](https://github.com/dhleong/playactor) library that is used by the add on to communicate with Playstation 4/5 devices. This library basically imitates the Remote Play feature. 

To discover devices `playactor` uses UDP broadcasting. I'm not a networking expert but a friend of mine, who is an expert, explained to that Broadcasts/Multicasts cannot leave the boundary of the network they're sent on. Which means to run the add on you _have to_ use the `host_network` flag.

So unfortunately this is a known limitation. If anything changes in the `playactor` implementation/Remote Play protocol we can re-open this issue. But until then I'll close it.

**Additional sources:**
[Thread](https://forums.docker.com/t/how-to-udp-broadcast-to-external-network-without-host-mode/86526/3) for more info on UDP Broadcasting and Docker.
