### ISSUE TITLE
Docker will not run

### ISSUE THREAD

**Issue by ninjanerdbgm** [FunkeyFlo/ps5-mqtt#263]
### Description of the issue

I'm having the following issue when trying to run ps5-mqtt from Docker:
![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/8430568/5f3a4860-d8f9-4cb5-a5ec-d68207e94759)

Here's my config:
![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/8430568/56bb7eb6-416a-47f7-bdfd-e18d54f71f0c)

Any idea on where I should look for any more info?  I'm new to Docker, so part of me thinks that I'm running the wrong command.

EDIT: If you need to see my run.sh, it's straight from the documentation:
![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/8430568/a65eefa8-b21a-4a62-a71c-e70106c2d73b)

### Addon version

Latest armv7

### Platform

I don't have a supervisor setting in my HA install.

**Comment by FunkeyFlo** [comment]
Have you checked that the run.sh is stored with correct line endings? (LF for Linux I believe).

**Comment by ninjanerdbgm** [comment]
Yeah, line endings should work (I wrote it in vim):

![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/8430568/5a76f384-d8c1-465d-a333-c4f7549c4afd)

**Comment by ninjanerdbgm** [comment]
I think I've tracked it down to something related to nodejs.  I have 18.16.1 installed.
