### ISSUE TITLE
[Feature request]: Separate different options to multiple text boxes in options

### ISSUE THREAD

**Issue by kristofferR** [FunkeyFlo/ps5-mqtt#28]
### Is your feature request related to a problem? Please describe

Right now the options are pretty confusing. I know my MQTT URL, my MQTT username and my MQTT password, but I don't know how to add them all to the single MQTT option text box. 

<img width="893" alt="Skjermbilde 2022-08-18 kl  18 23 08" src="https://user-images.githubusercontent.com/481270/185445664-354c04e1-f11b-47bf-bd85-f7ff6db59433.png">

### Describe the solution you'd like

The options should be separated logically instead. Like this for MQTT:

<img width="887" alt="Skjermbilde 2022-08-18 kl  18 21 06" src="https://user-images.githubusercontent.com/481270/185445428-a0a394d3-5868-4e90-89ff-b91b0cfd08a3.png">

It's the same for psn_accounts. I know my npsso, but adding both my username and npsso to a single text box is confusing.

**Comment by FunkeyFlo** [comment]
@kristofferR, I understand that some of the editors might be confusing for users who aren't that familiar with `.yaml` syntax.

But this is unfortunatly how Home Assistant renders complex values (`mqtt` config in this example) and list values (`psn_accounts` in this example). If you want that to change you should create a feature request on one of the Home Assistant repositories asking for "recursive configuration rendering" in for add-ons.

If you're still having trouble figuring out how to configure the add-on I suggest taking another look at the examples in the [documentation](https://github.com/FunkeyFlo/ps5-mqtt/blob/main/add-ons/ps5-mqtt/DOCS.md#example-configuration).

You could copy the example straight to your config using the `edit in YAML`  feature.
![Screenshot 2022-08-18 23 25 29](https://user-images.githubusercontent.com/4623715/185498409-3db816e8-8e0b-4c3d-9f0b-13ac50ad1edc.png)
