### ISSUE TITLE
Discovered entities with a name that starts with the device name

### ISSUE THREAD

**Issue by IceBotYT** [FunkeyFlo/ps5-mqtt#282]
### Description of the issue

Some MQTT entities have an entity name that starts with the device name. This is not expected. To avoid a duplicate name the device name prefix is stripped of the entity name as a work-a-round. Please inform the maintainer of the software application that supplies the affected entities to fix this issue.

https://developers.home-assistant.io/blog/2023-057-21-change-naming-mqtt-entities/

List of affected entities:

- sensor.ps5_***_activity
- switch.ps5_***_power

### Addon version

1.3.1

### Platform

Core: core-2023.8.0b3
Supervisor: supervisor-2023.07.3
Operating System: Home Assistant OS 10.4

**Comment by Stuke00** [comment]
I am seeing an error related to this.  Will it be updated?

**Comment by FunkeyFlo** [comment]
Yes, as soon as I am able to.

**Comment by skynet01** [comment]
We love you!

**Comment by IceBotYT** [comment]
Not stale

**Comment by phbasler** [comment]
@FunkeyFlo Can you make a release and new docker image containing this PR?

**Comment by FunkeyFlo** [comment]
Yeah, sorry it's taking so long. I was hoping to combine it with some other much anticipated features but we've just found out we're having twins and everything is totally bonkers right now. So I'm having trouble finding the time.

I'll try and release it this weekend. But no promises!

**Comment by IceBotYT** [comment]
Congratulations!

**Comment by phbasler** [comment]
Congratulations and strong nerves :)

**Comment by ultimateguy** [comment]
Any update on this? Still getting the same error

**Comment by mattclair** [comment]
Any update on this? Feb 2024 Home Assistant update will release in a few days and I won't be able to update until this issue is addressed.
