### ISSUE TITLE
Start on boot

### ISSUE THREAD

**Issue by fabiobaldoibs** [FunkeyFlo/ps5-mqtt#293]
### Description of the issue

I have the option start on boot = on, but do not work. I have to start manually every time

### Addon version

1.3.1

### Platform

core-2023.8.2
Home Assistant OS 10.4
supervisor-2023.08.1

**Comment by FunkeyFlo** [comment]
Without logs it's impossible to help

**Comment by fabiobaldoibs** [comment]
like that?

[21:49:31] ERROR: Got unexpected response from the API: Service not enabled
Starting PS5-MQTT...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: getaddrinfo ENOTFOUND null
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:109:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'null'
}

thanks!

**Comment by FunkeyFlo** [comment]
Have you installed an mqtt broker?

**Comment by fabiobaldoibs** [comment]
sorry, i've removed that.

now it is fine and working again. thaks
