### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by alsvartr** [FunkeyFlo/ps5-mqtt#309]
### Description of the issue

CPU usage on 1.3.1 around 20-30% when idle.

![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/205880/67ce911f-836e-4081-8ead-774a360d96ef)

### Addon version

1.3.1

### Platform

Home Assistant 2023.8.4
Supervisor 2023.08.3
Operating System 10.2
Frontend 20230802.1 - latest

### Hardware

Raspberry Pi 3
Single PS5

**Comment by FunkeyFlo** [comment]
Have you changed any of the default polling settings? You might want to increase them to see if that decreases the CPU usage.

Also, these are my own stats on a pi4 (8gb).

![Screenshot_20230913-185637](https://github.com/FunkeyFlo/ps5-mqtt/assets/4623715/66291ed1-9c43-45d3-b5ec-8a5b80c6ddf1)

P.s. HA themselves recommend using at least a pi4 with 2 gigs of ram.

**Comment by alsvartr** [comment]
Did not change anything

![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/205880/17fc6324-481e-4522-937d-f4f8b6bf319a)

Increasing device & account check intervals decreases CPU usage to ~10%. Not great not terrible. Still I don't understand why at all there is a CPU load in idle state?

**Comment by FunkeyFlo** [comment]
Because it is constantly checking whether a device has changed state (polling). Naturally this takes up compute cycles.
