### ISSUE TITLE
No longer getting title and image info

### ISSUE THREAD

**Issue by glassbase** [FunkeyFlo/ps5-mqtt#310]
### Description of the issue

Not getting any info for `title_name` and `title_image` recently. 

### Addon version

1.3.1

### Platform

Core: 2023.9.1

**Comment by FunkeyFlo** [comment]
Please include logs.

**Comment by glassbase** [comment]
```
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
Custom run.sh...
Starting PS5-MQTT...
```

**Comment by FunkeyFlo** [comment]
Is your account activity visible? (Not playing as "appear offline") Have you changed any of your privacy settings?

**Comment by glassbase** [comment]
I do not have appear offline set, no.

Did I change privacy settings? Don't think so

**Comment by FunkeyFlo** [comment]
> recently
This is what prompted me to ask if anything changed with your account settings. :)

I also take it that means it worked before?

Have you tried refreshing your npsso?

If the above doesn't work; please share your config.

**Comment by glassbase** [comment]
I did work before, yes... it still works for power status info, just not game title info and image. 
```
power: AWAKE
device_status: online
activity: idle
```

Will try and refresh token.

**Comment by FunkeyFlo** [comment]
Yeah, unfortunately the two features (device control and activity tracking) are controlled through different api's. Hence the two auth mechanisms required, the latter using the npsso.

I hoped the logs might contain an authentication error for your npsso 😂

**Comment by glassbase** [comment]
Ok works again. I did not realize npsso expires every 2 months. I will keep that in mind.
