### ISSUE TITLE
[Feature request]: Playing a movie "activity"

### ISSUE THREAD

**Issue by giulianoriccio** [FunkeyFlo/ps5-mqtt#332]
### Is your feature request related to a problem? Please describe

Is there any way to know when the PS5 is playing a movie?
At the moment the "activity" attribute stays "idle".

### Describe the solution you'd like

It could be useful if the value of the "activity" attribute could be changed to "movie" or something specific to the PS5 running a movie disc.

### Describe alternatives you've considered

As a last resort, if the type of activity cannot be identified, the "playing" value would still be better than nothing when playing a movie.

### Additional context

n/a

**Comment by Stuke00** [comment]
I would like this feature also

**Comment by FunkeyFlo** [comment]
Id love it too. But unfortunately it's not possible for the same reason you cannot see that a friend is watching a movie on PSN: Sony's APIs simply don't expose it.

Until that changes this feature isn't possible.
