### ISSUE TITLE
1.3.2 Addon version not compiled

### ISSUE THREAD

**Issue by inferno1231** [FunkeyFlo/ps5-mqtt#345]
### Description of the issue

Greetings,

Latest update (1.3.2) is not appearing in Home Assistant and is impossible to install. I am not sure, but I think something went wrong while compiling this addon version, any chance you could check it? Many thanks.

### Addon version

1.3.2

### Platform

Core
2023.11.3
Supervisor
2023.11.6
Operating System
11.1

**Comment by fwartner** [comment]
I managed to get it working: https://github.com/fwartner/ps5-mqtt

**Comment by brozikcz** [comment]
Hi @fwartner, thank you for your fix but why didn't create PR to this repo or at least create proper fork instead of copy / paste code to your new repository?

**Comment by fwartner** [comment]
Simply because I wanted to have this as quick as possible up and running and because I may add some new features in the future by myself that i need but that may dont get merged. :)

**Comment by abuchanan920** [comment]
Is this the reason there isn't an up to date docker container for the latest release? Or is that a separate issue?

**Comment by brozikcz** [comment]
I guess so, you can use the built image from my fork as a temporary solution https://github.com/brozikcz?tab=packages&repo_name=ps5-mqtt

**Comment by fwartner** [comment]
> I guess so, you can use the built image from my fork as a temporary solution https://github.com/brozikcz?tab=packages&repo_name=ps5-mqtt

https://github.com/fwartner?tab=packages&repo_name=ps5-mqtt :D

**Comment by FunkeyFlo** [comment]
Fixed with version 1.3.3
