### ISSUE TITLE
[Feature request]: Add Home Assistant discovery topic config option

### ISSUE THREAD

**Issue by RobertD502** [FunkeyFlo/ps5-mqtt#361]
### Is your feature request related to a problem? Please describe

Home Assistant allows user to set a custom discovery prefix instead of the default `homeassistant` discovery topic. As it stands, only users that use the default Home Assistant auto-discovery prefix have MQTT devices/entities created.

### Describe the solution you'd like

1. Create an optional home assistant discovery prefix config key
2. Use the user-set discovery topic when publishing to the MQTT broker (or the default `homeassistant` prefix if none is provided) instead of hardcoding the `homeassistant` prefix for all users (example of hardcoded prefix used [here](https://github.com/dror1544/ps5-mqtt/blob/c70cce992c5c5bc2ac900b0bcdda1a9e35e206e8/ps5-mqtt/server/src/redux/sagas/register-device.ts#L23)).

### Describe alternatives you've considered

No alternatives are available which would allow users with a non-default discovery topic to utilize this add-on.
Only manual option would be for users to define the MQTT sensor and switch on their own.

### Additional context

N/A

**Comment by MrIcemanLE** [comment]
Same problem here. I set up a custom discovery topic to connect two instances of HA. Please consider this option.

**Comment by RobertD502** [comment]
bump
