### ISSUE TITLE
MQTT to non-native VLAN

### ISSUE THREAD

**Issue by SpaceCowboyLive** [FunkeyFlo/ps5-mqtt#362]
### Description of the issue

Am unable to configure a Unifi router/switch to communicate with PS5 devices on a non-native VLAN. For example, Home Assistant is on VLAN1 and PS5 is on VLAN5. Despite VLAN1 being the native default VLAN for the network and all VLANs are allowed to communcate, Home Assistant is unable to connect to PS5 devices on VLAN5.

![Screenshot_20240103-152856_Home Assistant](https://github.com/FunkeyFlo/ps5-mqtt/assets/5692712/9073757f-ebd8-4aa5-9a08-ef695aa84763)
![Screenshot_20240103-152920](https://github.com/FunkeyFlo/ps5-mqtt/assets/5692712/16c988cf-5d51-4dcd-895c-85565dd24a52)
![Screenshot_20240103_153018](https://github.com/FunkeyFlo/ps5-mqtt/assets/5692712/6d3774b0-6322-4fc8-951d-d5308d45249a)

### Addon version

1.3.1

### Platform

Core: 2023.12.4
Supervisor: 2023.12.0
OS: 11.2

### Logs of the issue (if applicable)

N/A

**Comment by rudironsonijr** [comment]
I'm able to use the add-on on my IoT VLAN by creating a new virtual NIC for my home assistant VM and tagging it accordingly. I also selected  in Settings -> Network this NIC as the default one for integrations (I also have a default virtual NIC that connects to my "Servers-Trusted" VLAN).
I have firewall rules in my UDM-Pro blocking every every sensitive ports on the IP my HA IoT NIC get, like SSH, HTTP, HTTPS and the web UI.
This gave me the flexibility to connect my home assistant more easily to my IoT devices.

**Comment by rudironsonijr** [comment]
Also, you can try to specify the PS5 IP address in the option "device_discovery_broadcast_address".

> device_discovery_broadcast_address optional
> 
> IP address the addon will use for UDP broadcasting which is required for device discovery.
> 
> If your devices are located on a VLAN you must use this option to point the addon to the broadcast ip of the VLAN your devices are located on.
> 
> NOTE: only one broadcast address is supported. So all devices will need to be on the same VLAN.
