### ISSUE TITLE
new ps update 

### ISSUE THREAD

**Issue by mytering** [FunkeyFlo/ps5-mqtt#393]
### Description of the issue

activity shows idle even after playing game for 2 hours 

### Addon version

1.3.3

### Platform

ps system software 24.02-09.00.00.45-00.00.00.0.1

**Comment by mytering** [comment]
i think my npsso expired let me refresh ; read through the other issues

**Comment by mytering** [comment]
updated the npsso still idle

**Comment by jkramp** [comment]
I see that the code linked now has an option to exchange your npsso token. Does this mean we soon will not need to manually refresh it?

https://psn-api.achievements.app/authentication/authenticating-manually#exchange-your-npsso-token
