### ISSUE TITLE
Reduce CPU usage

### ISSUE THREAD

**Issue by Thrasher2020** [FunkeyFlo/ps5-mqtt#4]
### Description of the issue

Add-on using about 25-27% CPU - seems a bit excessive. 

![image](https://user-images.githubusercontent.com/65713394/177353524-61608129-55f8-4783-87d9-b8d03ea26b38.png)

### Addon version

0.4.2

### Platform

Home Assistant 2022.7.0b3
Supervisor 2022.06.2
Operating System 8.2
Frontend 20220630.0 - latest

**Comment by FunkeyFlo** [comment]
This is related to the [package](https://github.com/dhleong/playactor) that checks the PS5 status, etc. I changed two things in the release of version 0.4.3:
1. Only browse for devices at startup. As such decreasing system strain.
2. Added `device_check_interval` to the configuration. By default it's 1000ms, of course, increasing the value will improve performance, at the cost of receiving less updates. 🤷‍♂️

**Comment by FunkeyFlo** [comment]
For me (on a rpi4 8gb) 4500ms seems to be the Performance vs. Frequency sweetspot.

**Comment by alsvartr** [comment]
Hi, CPU usage on 1.3.1 still around 20-30% on idle.
![image](https://github.com/FunkeyFlo/ps5-mqtt/assets/205880/a01c7050-61e6-4a2e-a6e5-2bab90871891)

**Comment by FunkeyFlo** [comment]
@alsvartr in that case please open a new issue with detailed Hardware info included.

**Comment by alsvartr** [comment]
> @alsvartr in that case please open a new issue with detailed Hardware info included.

done
