### ISSUE TITLE
[Feature request]: link to npsso page on containers web page

### ISSUE THREAD

**Issue by Raytestrak** [FunkeyFlo/ps5-mqtt#418]
### Is your feature request related to a problem? Please describe

Every now and then, I need to refresh my npsso token. I need to look for the site every time, it would be helpful if the link to the npsso page would be accessible from the ps5mqtt container's page. 

### Describe the solution you'd like

In addition to the authenticate your PS5 button, another button to get your npsso token. The two go hand in hand, so it would be logical to have them side-by-side.

### Describe alternatives you've considered

Bookmarking the page XD

(I know that's the easiest option, but I really think it would make it using the add-on easier)

### Additional context

Thanks for this addon!

**Comment by RobertD502** [comment]
If you click on the documentation tab for the add-on, the link to the NPSSO token instructions is on there:

![Screen Shot 2024-06-13 at 9 30 40 PM](https://github.com/FunkeyFlo/ps5-mqtt/assets/52541649/3a3b0d23-c0db-47f9-b6b0-50d2724ad396)

**Comment by Raytestrak** [comment]
I think it would be complementary to the add-on to create a direct link to the [npsso](https://psn-api.achievements.app/authentication/authenticating-manually#get-started) page on the container's web page. I made a mock-up to show what I mean:

![ps5mqtt](https://github.com/FunkeyFlo/ps5-mqtt/assets/5616168/b0bcc583-7e02-4842-a2e7-438df13d395b)

**Comment by Raytestrak** [comment]
not stale imo

**Comment by FunkeyFlo** [comment]
Honestly, I don't think this would be a good location for adding documentation concerning the NPSSO. The web-ui is only meant for connecting your PS5 (device) to home-assistant using the remote-play feature.

Also, the mock you made isn't in line with how the configuration actually works. You don't provide a NPSSO per _device_. You provide one per _account_ you want to track.

I do see a use case of easy to access documentation for docker users, which don't have easy access to the docs like HA Supervised users do.

It might be an idea to include a configuration tab/menu item/page/w.e. to the web-ui that merely renders the Markdown file that's already in the repository.
