### ISSUE TITLE
Sony auth page says "Can't connect to the server" when 2FA is enabled

### ISSUE THREAD

**Issue by igorsantos07** [FunkeyFlo/ps5-mqtt#431]
### Description of the issue

I was able to install the add-on and it found my PS5, but following the auth page from Sony, I receive this error below:
![image](https://github.com/user-attachments/assets/cc8ee0cd-18e9-4597-be42-5e6c8b493afa)

I got a hint this was related to 2FA when I tried to sign in to a separate page, where it properly asked for the 2FA code after my password... But it looks like the session is not reused on the auth link provided, even though I'm also logged at the [Account Management page](https://my.account.sony.com/central/management), under the same domain.

I got to the `redirect` page after going to the link above and disabling 2FA.

I guess this is a limitation on the Sony side, so maybe you could just add a note to the setup popup explaining that 2FA must be disabled for the add-on to work? (not sure if re-enabling works after the auth, I'm having several issues with my HA as well after installing the add-on and couldn't wrap it up lol)

### Addon version

1.3.3

### Platform

...............

**Comment by RobertD502** [comment]
Are you referring to the steps for obtaining the NPSSO token? (the documentation seen below)

![image](https://github.com/user-attachments/assets/39832380-d351-45fb-a4fa-54840fad82bc)

If so, open the first link (`visit Playstation Homepage`) in a private browser session (incognito). Do the sign in there. Then, in the same private browsing session, visit the `this page` hyperlink from the documentation.

I've had this issue happen to me before (I also have 2FA setup) and getting the token via a private session got around this issue.

**Comment by igorsantos07** [comment]
Nope... I meant the initial auth when enabling the add-on. I just wanted to know if the PS5 was on or sleeping, so didn't even bother with the NPSSO thingie. I was only able to properly get to the `redirect` page when 2FA was disabled 🤷‍♂️

**Comment by RobertD502** [comment]
Same process for this step - I opened the authentication button in a private session, which circumvented the error. Never had to disable 2FA.

**Comment by igorsantos07** [comment]
Nice, didn't think about using a private session - just trying to log in before carrying on with the add-on procedure, but that didn't do the trick.

It is indeed Sony's fault, very odd. I would suggest not only a note in the README, but on the auth popup as well, as I mentioned in the start - it's where the user will definitely see what's going on, without going through the eventual frustration of "looking in docs for a solution".

**Comment by FunkeyFlo** [comment]
> Perhaps it may make sense to include a little note in the README about carrying out the authentication/NPSSO token acquisition in a private session

Agreed. Although my experience is that most people won't read it. But at least we'll get to say "rtfm". 😂 

> but on the auth popup as well

How do you imagine that would work? The pop-up is not managed by _this_ project.

**Comment by RobertD502** [comment]
> Agreed. Although my experience is that most people won't read it. But at least we'll get to say "rtfm". 😂

Perhaps the chance of that happening can be decreased by adding a little markdown pizzazz to catch the user's eye. Something like this:

> [!CAUTION]
> **NOTE HERE ABOUT PRIVATE SESSION** 

😬
