### ISSUE TITLE
Entities are unavailable after HA restart

### ISSUE THREAD

**Issue by Thrasher2020** [FunkeyFlo/ps5-mqtt#5]
### Description of the issue

The PS5 appears as unavailable despite MQTT getting traffic from the add-on. Using MQTT explorer I can see it being updated every 1s (or as close as).

Restarting the add-on multiple times will make the power entity "available" - I am not sure what is causing this odd behaviour.

![image](https://user-images.githubusercontent.com/65713394/177358190-9d3556b4-30db-4b55-83a7-bba13c4c3d47.png)

### Addon version

0.42

### Platform

Supervisor 2022.06.2
Operating System 8.2
Frontend 20220630.0 - latest

**Comment by FunkeyFlo** [comment]
Multiple questions:
1. What is the intended use of restarting the add-on "multiple" times?
2. The title of the issue reads HA (full home assistant?) restart and the description says restarting the add-on. Which is the correct one?
3. Is your PS5 in _standby_ or fully _off_? The add-on marks any ps5 it can no longer discover as 'offline'.

**Comment by Thrasher2020** [comment]
> Multiple questions:
> 
> 1. What is the intended use of restarting the add-on "multiple" times?
> 2. The title of the issue reads HA (full home assistant?) restart and the description says restarting the add-on. Which is the correct one?
> 3. Is your PS5 in _standby_ or fully _off_? The add-on marks any ps5 it can no longer discover as 'offline'.

1. When HA restarts the PS5 is unavailable. If you do nothing then it does not appear as available. Restarting the add-on once sometimes works, but generally it needs two add-on restarts after a HA restart.
2. Restarting HA.
3. In standby. It's never powered down.

**Comment by FunkeyFlo** [comment]
Apparently it's sending the availability messages at the wrong moment in time. I'll try fixing it somewhere this week.
