### ISSUE TITLE
[Feature request]: Vlan Support

### ISSUE THREAD

**Issue by ckunak** [FunkeyFlo/ps5-mqtt#57]
### Is your feature request related to a problem? Please describe

Can this be made to support PS5s on a diffrent Vlan then HA?

### Describe the solution you'd like

i cant seem to get the unit to discover over the vlan

### Describe alternatives you've considered

don't want to move ps5 to iot vlan

### Additional context

Thank you

**Comment by FunkeyFlo** [comment]
As far as I know this isn't possible. See [this reply](https://github.com/FunkeyFlo/ps5-mqtt/issues/25#issuecomment-1207484777) in #25

**Comment by FunkeyFlo** [comment]
As someone recently pointed out to me VLAN support is possible. The only feature that won't work is auto-discovery. So I'm suggesting the following.

1. The configuration will be expanded with a new option to declare a list of PS4/PS5 IP adresses.
2. The authentication web-ui will be expanded with a new option to authenticate with a device at a specified op. Meaning you will still have the option to acquire the required credentials without having to use the playactor cli tool.

**Comment by ckunak** [comment]
Awesome thanks

**Comment by omygolly** [comment]
Yes, pleease add manual IP. Can't get the addon to work on my Unifi-network with multiple vlans.

**Comment by NR005** [comment]
This would be really awesome. For me it somehow worked on a different vlan for a while, but stopped working after some update of either this add-on or home assistant itself.

**Comment by abuchanan920** [comment]
Manual IP would be helpful. It seems like there is a bug deep in the underlying library regarding discovery. It seems to want to broadcast on 255.255.255.255, which would normally be fine, but for some reason it insists on binding to the first network interface, which in my case is the externally facing one so it never sends the discovery packets on the internal interface. I've tried using the command line tool directly, but the cli options to bind to a specific address do not seem to work as expected. In my case, I got discover to work by patching the `/usr/local/lib/node_modules/playactor/dist/discovery/udp.js` file and modifying the line `const BROADCAST_ADDRESS = "255.255.255.255";` to point to a subnet that would work, such as "192.168.0.255" for example. Discovery worked fine after that.

**Comment by FunkeyFlo** [comment]
@NR005, @ckunak, @omygolly I've added a new option `device_discovery_broadcast_address` which allows you to manually set the broadcast IP. @abuchanan920 has confirmed this is working for the docker version but I'd love to get some more feedback from some more setups. Could you guys try out the latest `edge` version and let me know if this new setting fixes the issue for you? Thanks! ♥

**Comment by ckunak** [comment]
I installed the latest edge version today. I’ll play with tomorrow been busy with my new baby

**Comment by FunkeyFlo** [comment]
Thanks and congrats, hope you're getting some sleep! 😂

**Comment by ckunak** [comment]
> 

Thanks. Well i was able to get it going in home assistant. Mqtt is showing when the device is on or off. I can’t get the power on or psn working. I’ll will play with it more in a day or two

**Comment by FunkeyFlo** [comment]
@ckunak were you able to perform the authentication steps with the device using the web interface? 

If no credentials are present standby / wake will not work.

**Comment by ckunak** [comment]
> @ckunak were you able to perform the authentication steps with the device using the web interface?
> 
> If no credentials are present standby / wake will not work.

yes i did.  the remote screen on the ps5 closed once connected.
is the  username: and  npsso:  needed? if so is the username my email or display name on psn?

**Comment by eSeR1805** [comment]
@FunkeyFlo this update fixes it for me. Cheers!

**Comment by FunkeyFlo** [comment]
@eSeR1805 that's great to hear! Love to finally get some feedback on the request. ❤️

Just to verify, were you able to verify that the following features worked properly with the current `edge` version?
- [ ] power state tracking of devices (over an extended period of time)
- [ ] automatic device discovery
- [ ] web-ui authentication
- [ ] activity tracking

And I'm also interested in knowing what device/kind of setup you've tested these features on.

**Comment by eSeR1805** [comment]
Confirming it's `edge` (installed yesterday) and auto discovery works with specified IP through `device_discovery_broadcast_address` config entry
![image](https://user-images.githubusercontent.com/61332999/203001586-e286a295-ad81-416c-b6b9-0d4312b3f663.png)
Web-ui authentication worked and below are power state and activity tracking:
![image](https://user-images.githubusercontent.com/61332999/203001993-ccb05866-a72d-4760-86c0-6d1afbb774a6.png)
![image](https://user-images.githubusercontent.com/61332999/203002142-d404eb5d-edb8-4298-a786-d5618f0d6492.png)
Not that extensive period yet but I'll let you know if I notice anything funky these days.

Setup:
- HA running in VM (Unraid machine on my main LAN)
- PS5 running on separate VLAN

**Comment by FunkeyFlo** [comment]
@ckunak & @eSeR1805, thank you guys for verifying the change. Hopefully I'll be able to create a new stable release tonight!

**Comment by velodromen** [comment]
I had some issues with this until i decided to **use the IP address of my PS5 instead of the VLAN broadcast address**. I don't know if it's just my setup but if it's the actual device IP that should be used here then the description should be changed from:
_device_discovery_broadcast_address_ 

to

_console_ip_address_
