### ISSUE TITLE
unreliable wakeup/sleep

### ISSUE THREAD

**Issue by tungmeister** [FunkeyFlo/ps5-mqtt#6]
### Description of the issue

when using the addon the majority of the time wakeup/sleep doesn't work and throws a 403 error. If I use playactor directly it works every time.

### Addon version

0.4.4

### Platform

2022.7.3 hassos

### Logs of the issue (if applicable)
```
Creating ps5 credentials file!
Starting PS5 MQTT Client
2022-07-13T22:33:48.508Z @ha:ps5 Started
2022-07-13T22:34:13.810Z @ha:ps5:turnOnDevice [String: ''] {
  stdout: '',
  stderr: '',
  code: 0,
  cat: [Function: bound ],
  exec: [Function: bound ],
  grep: [Function: bound ],
  head: [Function: bound ],
  sed: [Function: bound ],
  sort: [Function: bound ],
  tail: [Function: bound ],
  to: [Function: bound ],
  toEnd: [Function: bound ],
  uniq: [Function: bound ]
}
2022-07-13T22:35:21.108Z @ha:ps5:turnOffDevice [String: ''] {
  stdout: '',
  stderr: 'Error: Registration error: 403: Forbidden: Other Error\n' +
    '    at Object.<anonymous> (/usr/local/lib/node_modules/playactor/dist/remoteplay/protocol.js:88:19)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (/usr/local/lib/node_modules/playactor/dist/remoteplay/protocol.js:5:58)\n' +
    '    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n',
  code: 1,
  cat: [Function: bound ],
  exec: [Function: bound ],
  grep: [Function: bound ],
  head: [Function: bound ],
  sed: [Function: bound ],
  sort: [Function: bound ],
  tail: [Function: bound ],
  to: [Function: bound ],
  toEnd: [Function: bound ],
  uniq: [Function: bound ]
}
TypeError: errorLogger is not a function
    at /app/dist/redux/sagas/check-devices-state.js:76:17
    at step (/app/dist/redux/sagas/check-devices-state.js:24:23)
    at Object.next (/app/dist/redux/sagas/check-devices-state.js:5:53)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1161:27)
    at currCb (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1255:7)
    at runSelectEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:735:5)
    at runEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1208:7)
    at digestEffect (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1275:5)
    at next (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1165:9)
    at proc (/app/node_modules/@redux-saga/core/dist/redux-saga-core.dev.cjs.js:1112:3)
The above error occurred in task checkDevicesState
    created by takeLatest(CHECK_DEVICES_STATE, checkDevicesState)
    created by checkDevicesStateSaga
    created by saga
Tasks cancelled due to error:
takeLatest(CHECK_DEVICES_STATE, checkDevicesState)
delayForTransitionSaga
discoverDevicesSaga
addDevicesSaga
turnOnSaga
turnOffSaga
updateHomeAssistantSaga
pollPs5StatesSaga
pollDisoverySaga
```

**Comment by FunkeyFlo** [comment]
Are there any things _different_ when it does work or doesn't work?
- Is the PlayStation _on_ when the add on starts?
- Is the PS5's ip changing?
- etc.

Have you tried:
- restarting the add-on help?
- checking that the credentials are valid JSON?
- etc.

I also see [multiple issues with playactor regarding 403 errors](https://github.com/dhleong/playactor/issues?q=is%3Aissue+is%3Aopen+403) have you checked those out?

**Comment by tungmeister** [comment]
restarting the addon might resolve it for the first press of the button but after that it will go back to being broken - as in toggling the switch doesn't action any change. The credentails are valid json as it can work some of the time and are a direct copy from the
playactor config. I tried several on/off with playactor direct over a period of time and they all worked perfectly. The IP address is on an infinate lease. 
I'll have another play after work tonight and see if I can get anything more useful for you.

**Comment by FunkeyFlo** [comment]
@tungmeister, Unless you are running playactor on the _exact_ same setup as the Home Assistant add-on; same container, same host, same network, same OS, etc. etc. it really doesn't mean that the issue is not related to playactor. As you can imagine, multiple things might be different between your own computer or an add-on running in  your Home Assistant setup.

Because I cannot replicate this behavior on my own setup I will need more information to provide any further help. 
Any extra info you could gather would be helpful. 
Maybe stuff like:
- What device you are running home assistant on.
- Firewall rules / exotic network config, etc.
- Are you using a PIN code for unlocking your Playstation?
- etc.

**Comment by FunkeyFlo** [comment]
Assuming this is no longer an issue due to inactivity.
