### ISSUE TITLE
[Feature request]: Expose in HA as media player

### ISSUE THREAD

**Issue by denysdovhan** [FunkeyFlo/ps5-mqtt#63]
### Is your feature request related to a problem? Please describe

PS4 used to be exposed in HA as media_player entity. I think it would be nice to see ps5_activity and ps5_power to be merged into a single media_player entity, if this is possible.

### Describe the solution you'd like

Adding an ability to expose ps5 as a media_player entity.

### Describe alternatives you've considered

I was thinking about using universal player integration to achieve the similar result, but it will not display game posters of the currently playing game.

https://www.home-assistant.io/integrations/universal/

### Additional context

See: https://www.home-assistant.io/integrations/ps4/

**Comment by FunkeyFlo** [comment]
This is not an option at this time because Home Assistant (currently) does not support MQTT `media_player` [entities](https://www.home-assistant.io/docs/mqtt/discovery/).

The PS4 integration isn't limited by MQTT like the add on is. Which is one of the reasons why that integration is still recommended for using PS4 devices.

Should HA add support for MQTT `media_player` entities we could re-open this request.

**Comment by sh00t2kill** [comment]
you COULD use the universal media player integration and set it up that way.
I mostly have this working just need to get the configuration right.

**Comment by sh00t2kill** [comment]
https://github.com/Sennevds/media_player.template

That custom media player integration functions similar to the universal one, only it allows you to set an image.
I have it working with ps5-mqtt

**Comment by glassbase** [comment]
Updated version with credit to @sh00t2kill starting point.

'''
media_player:
  - platform: media_player_template
    media_players:
      ps5:
        device_class: tv
        unique_id: media_player.ps5
        friendly_name: "PS5"

        media_image_url_template: >
          {% if states('sensor.ps5_activity') == "playing" %}
            {{ state_attr('sensor.ps5_activity','title_image') }}
          {% endif %}

        turn_off:
          data_template:
            entity_id: switch.ps5_power
          service: switch.turn_off

        turn_on:
          data_template:
            entity_id: switch.ps5_power
          service: switch.turn_on

        current_source_template: "{{ state_attr('sensor.ps5_activity','title_name') }}"

        value_template: "{{ states('switch.ps5_power') }}"

        title_template: "{{ state_attr('sensor.ps5_activity','title_name') }}"
'''
