### ISSUE TITLE
Addon not starting

### ISSUE THREAD

**Issue by Jordenjj** [FunkeyFlo/ps5-mqtt#70]
### Description of the issue

When starting the addon, it takes a few seconds before it shuts down again. 

Any thoughts? Log below.

Thanks for developing this!

### Addon version

1.0.1

### Platform

Home Assistant 2022.9.1
Supervisor 2022.08.6
Operating System 8.5
Frontend 20220907.0 - latest

RPI 4

### Logs of the issue (if applicable)

```
[15:34:49] ERROR: Got unexpected response from the API: Service not enabled
Starting PS5-MQTT...
node:internal/process/promises:279
            triggerUncaughtException(err, true /* fromPromise */);
            ^
Error: getaddrinfo ENOTFOUND null
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26) {
  errno: -3008,
  code: 'ENOTFOUND',
  syscall: 'getaddrinfo',
  hostname: 'null'
}
```

**Comment by FunkeyFlo** [comment]
You are using the `edge` version. It is highly discouraged for daily use. As mentioned in the documentation (please read it) that it is highly discouraged to use the `edge` version for daily use.

**Do not create issues for the `edge` version**

**Comment by Jordenjj** [comment]
@FunkeyFlo 
Thanks for the quick response, however im not! I downloaded the correct version please see the images below.

<img width="958" alt="Screenshot 2022-09-11 at 15 47 52" src="https://user-images.githubusercontent.com/14220294/189531019-11b277ef-69eb-40e9-ad69-92c6b57db1b8.png">
<img width="1034" alt="Screenshot 2022-09-11 at 15 47 42" src="https://user-images.githubusercontent.com/14220294/189531020-f3145aa8-6223-4afb-b259-cf5a65694579.png">

**Comment by FunkeyFlo** [comment]
That is incredibly strange. The stable version hasn't changed in almost a month and only the edge version has received updates in that time frame.

Did you *just now* install the add-on? Or did the issue occur after an update?

**Comment by Jordenjj** [comment]
> That is incredibly strange. The stable version hasn't changed in almost a month and only the edge version has received updates in that time frame.
> 
> Did you _just now_ install the add-on? Or did the issue occur after an update?

Just now, first time.

**Comment by FunkeyFlo** [comment]
Did you install an MQTT broker?

**Comment by Jordenjj** [comment]
> Did you install an MQTT broker?

Not manually, but I'm running Z-Wave JS to MQTT, which works.

**Comment by FunkeyFlo** [comment]
I'm not familiar with that add-on but based on a quick read I'm guessing it doesn't have a hard requirement on a separate MQTT broker. This add-on, however, does.
