### ISSUE TITLE
!secret not working 

### ISSUE THREAD

**Issue by Shiroe93** [FunkeyFlo/ps5-mqtt#91]
### Description of the issue

For some reason when I try to hide my token behind !secret i get this error 

### Addon version

Latest 

### Platform

Everything updated to last version 

### Logs of the issue (if applicable)

![Screenshot_20221002_034334_Home Assistant](https://user-images.githubusercontent.com/56954468/193434430-18f385b7-f701-4681-8e52-b5d14f4f0579.jpg)

**Comment by Shiroe93** [comment]
In the exact moment that I press the publish button I was trying to modify it from  my phone and it worked for some reason

**Comment by FunkeyFlo** [comment]
Glad it worked out. But for next time: please include the configuration in `yaml` format. Without it I really can't help.

**Comment by Shiroe93** [comment]
Will do and thank you for the response
