### ISSUE TITLE
[Feature request]: add to HACS

### ISSUE THREAD

**Issue by user897943** [FunkeyFlo/ps5-mqtt#92]
### Is your feature request related to a problem? Please describe

Please offer this as a HACS addon

### Describe the solution you'd like

I run HA on Docker so can't install this using the home assistant OS add-on store

### Describe alternatives you've considered

I'm not aware of alternatives?!

### Additional context

See above

**Comment by FunkeyFlo** [comment]
HACS only supports integrations, not add-ons.

If you want to use this add-on with docker already is documentation in the repo on how to do this...

**Comment by user897943** [comment]
Thanks I'll take a look at the docker approach. Is it docker-cli or docker-compose? I don't use compose.
